/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getParametroConexionAccess().getAlternatives(), "rule__ParametroConexion__Alternatives");
					put(grammarAccess.getRecursoAccess().getAlternatives(), "rule__Recurso__Alternatives");
					put(grammarAccess.getMecanismoSeguridadAccess().getAlternatives(), "rule__MecanismoSeguridad__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getNombreAmbienteAccess().getAlternatives(), "rule__NombreAmbiente__Alternatives");
					put(grammarAccess.getTamanioServidorAccess().getAlternatives(), "rule__TamanioServidor__Alternatives");
					put(grammarAccess.getSistemaOperativoAccess().getAlternatives(), "rule__SistemaOperativo__Alternatives");
					put(grammarAccess.getManejadorSQLAccess().getAlternatives(), "rule__ManejadorSQL__Alternatives");
					put(grammarAccess.getManejadorNoSQLAccess().getAlternatives(), "rule__ManejadorNoSQL__Alternatives");
					put(grammarAccess.getProtocoloAccess().getAlternatives(), "rule__Protocolo__Alternatives");
					put(grammarAccess.getInfraestructuraAccess().getGroup(), "rule__Infraestructura__Group__0");
					put(grammarAccess.getProveedorAccess().getGroup(), "rule__Proveedor__Group__0");
					put(grammarAccess.getProveedorAccess().getGroup_6(), "rule__Proveedor__Group_6__0");
					put(grammarAccess.getProveedorAccess().getGroup_6_4(), "rule__Proveedor__Group_6_4__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup(), "rule__AmbienteDespliegue__Group__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_2(), "rule__AmbienteDespliegue__Group_2__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_3(), "rule__AmbienteDespliegue__Group_3__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_3_3(), "rule__AmbienteDespliegue__Group_3_3__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_4(), "rule__AmbienteDespliegue__Group_4__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_4_3(), "rule__AmbienteDespliegue__Group_4_3__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_5(), "rule__AmbienteDespliegue__Group_5__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_5_3(), "rule__AmbienteDespliegue__Group_5_3__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_6(), "rule__AmbienteDespliegue__Group_6__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_6_5(), "rule__AmbienteDespliegue__Group_6_5__0");
					put(grammarAccess.getUsuarioPasswordAccess().getGroup(), "rule__UsuarioPassword__Group__0");
					put(grammarAccess.getUsuarioPasswordAccess().getGroup_3(), "rule__UsuarioPassword__Group_3__0");
					put(grammarAccess.getUsuarioPasswordAccess().getGroup_4(), "rule__UsuarioPassword__Group_4__0");
					put(grammarAccess.getLlaveAccess().getGroup(), "rule__Llave__Group__0");
					put(grammarAccess.getLlaveAccess().getGroup_3(), "rule__Llave__Group_3__0");
					put(grammarAccess.getConexionAccess().getGroup(), "rule__Conexion__Group__0");
					put(grammarAccess.getConexionAccess().getGroup_2(), "rule__Conexion__Group_2__0");
					put(grammarAccess.getConexionAccess().getGroup_6(), "rule__Conexion__Group_6__0");
					put(grammarAccess.getVPCAccess().getGroup(), "rule__VPC__Group__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup(), "rule__ServidorAplicaciones__Group__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_2(), "rule__ServidorAplicaciones__Group_2__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_3(), "rule__ServidorAplicaciones__Group_3__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_4(), "rule__ServidorAplicaciones__Group_4__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_5(), "rule__ServidorAplicaciones__Group_5__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_5_3(), "rule__ServidorAplicaciones__Group_5_3__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup(), "rule__ServidorAlmacenamiento__Group__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup_2(), "rule__ServidorAlmacenamiento__Group_2__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup_3(), "rule__ServidorAlmacenamiento__Group_3__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup_4(), "rule__ServidorAlmacenamiento__Group_4__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup_5(), "rule__ServidorAlmacenamiento__Group_5__0");
					put(grammarAccess.getServidorAlmacenamientoAccess().getGroup_5_3(), "rule__ServidorAlmacenamiento__Group_5_3__0");
					put(grammarAccess.getBaseDatosSQLAccess().getGroup(), "rule__BaseDatosSQL__Group__0");
					put(grammarAccess.getBaseDatosSQLAccess().getGroup_2(), "rule__BaseDatosSQL__Group_2__0");
					put(grammarAccess.getBaseDatosSQLAccess().getGroup_3(), "rule__BaseDatosSQL__Group_3__0");
					put(grammarAccess.getBaseDatosSQLAccess().getGroup_4(), "rule__BaseDatosSQL__Group_4__0");
					put(grammarAccess.getBaseDatosSQLAccess().getGroup_5(), "rule__BaseDatosSQL__Group_5__0");
					put(grammarAccess.getBaseDatosSQLAccess().getGroup_5_3(), "rule__BaseDatosSQL__Group_5_3__0");
					put(grammarAccess.getBaseDatosNoSQLAccess().getGroup(), "rule__BaseDatosNoSQL__Group__0");
					put(grammarAccess.getBaseDatosNoSQLAccess().getGroup_2(), "rule__BaseDatosNoSQL__Group_2__0");
					put(grammarAccess.getBaseDatosNoSQLAccess().getGroup_3(), "rule__BaseDatosNoSQL__Group_3__0");
					put(grammarAccess.getBaseDatosNoSQLAccess().getGroup_4(), "rule__BaseDatosNoSQL__Group_4__0");
					put(grammarAccess.getBaseDatosNoSQLAccess().getGroup_5(), "rule__BaseDatosNoSQL__Group_5__0");
					put(grammarAccess.getBaseDatosNoSQLAccess().getGroup_5_3(), "rule__BaseDatosNoSQL__Group_5_3__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getInternetGatewayAccess().getGroup(), "rule__InternetGateway__Group__0");
					put(grammarAccess.getInternetGatewayAccess().getGroup_2(), "rule__InternetGateway__Group_2__0");
					put(grammarAccess.getSubredAccess().getGroup(), "rule__Subred__Group__0");
					put(grammarAccess.getSubredAccess().getGroup_2(), "rule__Subred__Group_2__0");
					put(grammarAccess.getSubredAccess().getGroup_3(), "rule__Subred__Group_3__0");
					put(grammarAccess.getSubredAccess().getGroup_4(), "rule__Subred__Group_4__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup(), "rule__GrupoSeguridad__Group__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_2(), "rule__GrupoSeguridad__Group_2__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_3(), "rule__GrupoSeguridad__Group_3__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_6(), "rule__GrupoSeguridad__Group_6__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_6_3(), "rule__GrupoSeguridad__Group_6_3__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_7(), "rule__GrupoSeguridad__Group_7__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_7_3(), "rule__GrupoSeguridad__Group_7_3__0");
					put(grammarAccess.getReglaAccess().getGroup(), "rule__Regla__Group__0");
					put(grammarAccess.getReglaAccess().getGroup_3(), "rule__Regla__Group_3__0");
					put(grammarAccess.getReglaAccess().getGroup_4(), "rule__Regla__Group_4__0");
					put(grammarAccess.getReglaAccess().getGroup_5(), "rule__Regla__Group_5__0");
					put(grammarAccess.getReglaAccess().getGroup_6(), "rule__Regla__Group_6__0");
					put(grammarAccess.getReglaAccess().getGroup_7(), "rule__Regla__Group_7__0");
					put(grammarAccess.getInfraestructuraAccess().getNombreAssignment_1(), "rule__Infraestructura__NombreAssignment_1");
					put(grammarAccess.getInfraestructuraAccess().getProveedorAssignment_3(), "rule__Infraestructura__ProveedorAssignment_3");
					put(grammarAccess.getProveedorAccess().getNombreAssignment_2(), "rule__Proveedor__NombreAssignment_2");
					put(grammarAccess.getProveedorAccess().getParametroConexionAssignment_5(), "rule__Proveedor__ParametroConexionAssignment_5");
					put(grammarAccess.getProveedorAccess().getAmbientesDespliegueAssignment_6_3(), "rule__Proveedor__AmbientesDespliegueAssignment_6_3");
					put(grammarAccess.getProveedorAccess().getAmbientesDespliegueAssignment_6_4_1(), "rule__Proveedor__AmbientesDespliegueAssignment_6_4_1");
					put(grammarAccess.getAmbienteDespliegueAccess().getNombreAssignment_2_2(), "rule__AmbienteDespliegue__NombreAssignment_2_2");
					put(grammarAccess.getAmbienteDespliegueAccess().getRecursosAssignment_3_2(), "rule__AmbienteDespliegue__RecursosAssignment_3_2");
					put(grammarAccess.getAmbienteDespliegueAccess().getRecursosAssignment_3_3_1(), "rule__AmbienteDespliegue__RecursosAssignment_3_3_1");
					put(grammarAccess.getAmbienteDespliegueAccess().getConexionesAssignment_4_2(), "rule__AmbienteDespliegue__ConexionesAssignment_4_2");
					put(grammarAccess.getAmbienteDespliegueAccess().getConexionesAssignment_4_3_1(), "rule__AmbienteDespliegue__ConexionesAssignment_4_3_1");
					put(grammarAccess.getAmbienteDespliegueAccess().getSeguridadAssignment_5_2(), "rule__AmbienteDespliegue__SeguridadAssignment_5_2");
					put(grammarAccess.getAmbienteDespliegueAccess().getSeguridadAssignment_5_3_1(), "rule__AmbienteDespliegue__SeguridadAssignment_5_3_1");
					put(grammarAccess.getAmbienteDespliegueAccess().getVpcAssignment_6_4(), "rule__AmbienteDespliegue__VpcAssignment_6_4");
					put(grammarAccess.getAmbienteDespliegueAccess().getVpcAssignment_6_5_1(), "rule__AmbienteDespliegue__VpcAssignment_6_5_1");
					put(grammarAccess.getUsuarioPasswordAccess().getUsuarioAssignment_3_1(), "rule__UsuarioPassword__UsuarioAssignment_3_1");
					put(grammarAccess.getUsuarioPasswordAccess().getPasswordAssignment_4_1(), "rule__UsuarioPassword__PasswordAssignment_4_1");
					put(grammarAccess.getLlaveAccess().getSecretoAssignment_3_1(), "rule__Llave__SecretoAssignment_3_1");
					put(grammarAccess.getConexionAccess().getNombreAssignment_2_1(), "rule__Conexion__NombreAssignment_2_1");
					put(grammarAccess.getConexionAccess().getRecursosAssignment_5(), "rule__Conexion__RecursosAssignment_5");
					put(grammarAccess.getConexionAccess().getRecursosAssignment_6_1(), "rule__Conexion__RecursosAssignment_6_1");
					put(grammarAccess.getVPCAccess().getNombreAssignment_5(), "rule__VPC__NombreAssignment_5");
					put(grammarAccess.getServidorAplicacionesAccess().getNombreAssignment_2_1(), "rule__ServidorAplicaciones__NombreAssignment_2_1");
					put(grammarAccess.getServidorAplicacionesAccess().getTamanioAssignment_3_1(), "rule__ServidorAplicaciones__TamanioAssignment_3_1");
					put(grammarAccess.getServidorAplicacionesAccess().getSistemaOperativoAssignment_4_1(), "rule__ServidorAplicaciones__SistemaOperativoAssignment_4_1");
					put(grammarAccess.getServidorAplicacionesAccess().getConexionesAssignment_5_2(), "rule__ServidorAplicaciones__ConexionesAssignment_5_2");
					put(grammarAccess.getServidorAplicacionesAccess().getConexionesAssignment_5_3_1(), "rule__ServidorAplicaciones__ConexionesAssignment_5_3_1");
					put(grammarAccess.getServidorAplicacionesAccess().getVpcAssignment_7(), "rule__ServidorAplicaciones__VpcAssignment_7");
					put(grammarAccess.getServidorAlmacenamientoAccess().getNombreAssignment_2_1(), "rule__ServidorAlmacenamiento__NombreAssignment_2_1");
					put(grammarAccess.getServidorAlmacenamientoAccess().getTamanioAssignment_3_1(), "rule__ServidorAlmacenamiento__TamanioAssignment_3_1");
					put(grammarAccess.getServidorAlmacenamientoAccess().getTamanioInicialAssignment_4_1(), "rule__ServidorAlmacenamiento__TamanioInicialAssignment_4_1");
					put(grammarAccess.getServidorAlmacenamientoAccess().getConexionesAssignment_5_2(), "rule__ServidorAlmacenamiento__ConexionesAssignment_5_2");
					put(grammarAccess.getServidorAlmacenamientoAccess().getConexionesAssignment_5_3_1(), "rule__ServidorAlmacenamiento__ConexionesAssignment_5_3_1");
					put(grammarAccess.getServidorAlmacenamientoAccess().getVpcAssignment_7(), "rule__ServidorAlmacenamiento__VpcAssignment_7");
					put(grammarAccess.getBaseDatosSQLAccess().getNombreAssignment_2_1(), "rule__BaseDatosSQL__NombreAssignment_2_1");
					put(grammarAccess.getBaseDatosSQLAccess().getTamanioAssignment_3_1(), "rule__BaseDatosSQL__TamanioAssignment_3_1");
					put(grammarAccess.getBaseDatosSQLAccess().getManejadorAssignment_4_1(), "rule__BaseDatosSQL__ManejadorAssignment_4_1");
					put(grammarAccess.getBaseDatosSQLAccess().getConexionesAssignment_5_2(), "rule__BaseDatosSQL__ConexionesAssignment_5_2");
					put(grammarAccess.getBaseDatosSQLAccess().getConexionesAssignment_5_3_1(), "rule__BaseDatosSQL__ConexionesAssignment_5_3_1");
					put(grammarAccess.getBaseDatosSQLAccess().getVpcAssignment_7(), "rule__BaseDatosSQL__VpcAssignment_7");
					put(grammarAccess.getBaseDatosNoSQLAccess().getNombreAssignment_2_1(), "rule__BaseDatosNoSQL__NombreAssignment_2_1");
					put(grammarAccess.getBaseDatosNoSQLAccess().getTamanioAssignment_3_1(), "rule__BaseDatosNoSQL__TamanioAssignment_3_1");
					put(grammarAccess.getBaseDatosNoSQLAccess().getManejadorAssignment_4_1(), "rule__BaseDatosNoSQL__ManejadorAssignment_4_1");
					put(grammarAccess.getBaseDatosNoSQLAccess().getConexionesAssignment_5_2(), "rule__BaseDatosNoSQL__ConexionesAssignment_5_2");
					put(grammarAccess.getBaseDatosNoSQLAccess().getConexionesAssignment_5_3_1(), "rule__BaseDatosNoSQL__ConexionesAssignment_5_3_1");
					put(grammarAccess.getBaseDatosNoSQLAccess().getVpcAssignment_7(), "rule__BaseDatosNoSQL__VpcAssignment_7");
					put(grammarAccess.getInternetGatewayAccess().getNombreAssignment_2_1(), "rule__InternetGateway__NombreAssignment_2_1");
					put(grammarAccess.getInternetGatewayAccess().getVpcAssignment_4(), "rule__InternetGateway__VpcAssignment_4");
					put(grammarAccess.getSubredAccess().getNombreAssignment_2_1(), "rule__Subred__NombreAssignment_2_1");
					put(grammarAccess.getSubredAccess().getCIDRAssignment_3_1(), "rule__Subred__CIDRAssignment_3_1");
					put(grammarAccess.getSubredAccess().getZonaDisponibilidadAssignment_4_1(), "rule__Subred__ZonaDisponibilidadAssignment_4_1");
					put(grammarAccess.getSubredAccess().getVpcAssignment_6(), "rule__Subred__VpcAssignment_6");
					put(grammarAccess.getGrupoSeguridadAccess().getNombreAssignment_2_1(), "rule__GrupoSeguridad__NombreAssignment_2_1");
					put(grammarAccess.getGrupoSeguridadAccess().getDescripcionAssignment_3_1(), "rule__GrupoSeguridad__DescripcionAssignment_3_1");
					put(grammarAccess.getGrupoSeguridadAccess().getVpcAssignment_5(), "rule__GrupoSeguridad__VpcAssignment_5");
					put(grammarAccess.getGrupoSeguridadAccess().getReglasEntradaAssignment_6_2(), "rule__GrupoSeguridad__ReglasEntradaAssignment_6_2");
					put(grammarAccess.getGrupoSeguridadAccess().getReglasEntradaAssignment_6_3_1(), "rule__GrupoSeguridad__ReglasEntradaAssignment_6_3_1");
					put(grammarAccess.getGrupoSeguridadAccess().getReglasSalidaAssignment_7_2(), "rule__GrupoSeguridad__ReglasSalidaAssignment_7_2");
					put(grammarAccess.getGrupoSeguridadAccess().getReglasSalidaAssignment_7_3_1(), "rule__GrupoSeguridad__ReglasSalidaAssignment_7_3_1");
					put(grammarAccess.getReglaAccess().getTipoAssignment_3_1(), "rule__Regla__TipoAssignment_3_1");
					put(grammarAccess.getReglaAccess().getProtocoloAssignment_4_1(), "rule__Regla__ProtocoloAssignment_4_1");
					put(grammarAccess.getReglaAccess().getPuertoAssignment_5_1(), "rule__Regla__PuertoAssignment_5_1");
					put(grammarAccess.getReglaAccess().getOrigenAssignment_6_1(), "rule__Regla__OrigenAssignment_6_1");
					put(grammarAccess.getReglaAccess().getDescripcionAssignment_7_1(), "rule__Regla__DescripcionAssignment_7_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalMyDslParser typedParser = (InternalMyDslParser) parser;
			typedParser.entryRuleInfraestructura();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
